import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowRight, ArrowUpRight, Compass, MapPin, MoveRight } from "lucide-react";
import hero from "@/assets/new-hero.jpg";
import { Button } from "@/components/ui/button";
import { DiscoverySearch } from "@/components/discovery-search";
import { HomeTile } from "@/components/home-tile";
import { homes } from "@/lib/catalog";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "HouseProvider.in — Find a place that feels like home" },
    { name: "description", content: "Discover thoughtfully presented fictional homes across India. Search by location, property type and budget." },
    { property: "og:title", content: "HouseProvider.in — Find a place that feels like home" },
    { property: "og:description", content: "An original way to explore homes across India." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: HomePage,
});
function HomePage() { return <main>
  <section className="hero"><img src={hero} alt="Sunlit contemporary living room with a plum sofa and garden outlook" className="hero-photo" width={1600} height={1056} fetchPriority="high"/><div className="hero-overlay"/><div className="wrap hero-layout"><div className="hero-copy"><p className="hero-label"><span/> A NEW WAY TO FIND YOUR PLACE</p><h1>Find a place<br/>that feels like <em>home.</em></h1><p className="hero-description">Discover homes, neighborhoods and spaces intelligently — based on how you actually want to live.</p><div className="hero-ctas"><Button asChild className="hero-primary"><Link to="/properties">Find My Home <ArrowUpRight size={18}/></Link></Button><Link to="/list-property" className="hero-secondary">List Your Property <ArrowRight size={17}/></Link></div></div><div className="hero-foot"><span>SPACES FOR THE WAY YOU LIVE</span><a href="#discover" aria-label="Scroll to search"><ArrowDown size={19}/></a><span>01 — DISCOVER</span></div></div></section>
  <section className="discover-section" id="discover"><div className="wrap"><div className="section-heading"><div><p className="kicker">THE SEARCH STARTS HERE</p><h2>Where do you want<br/>to <em>live?</em></h2></div><p>Every new beginning starts somewhere. Tell us what matters most, and find a space that feels right.</p></div><DiscoverySearch/><div className="quick-cities"><span>EXPLORE BY CITY</span>{["Pune", "Mumbai", "Bengaluru", "Delhi NCR"].map(city => <Link to="/properties" search={{ location: city }} key={city}>{city} <ArrowUpRight size={13}/></Link>)}</div></div></section>
  <section className="featured-section"><div className="wrap"><div className="feature-heading"><div><p className="kicker">THE COLLECTION / 01</p><h2>Spaces with <em>possibility.</em></h2></div><Button asChild variant="outline" className="outline-cta"><Link to="/properties">Explore all homes <ArrowUpRight size={16}/></Link></Button></div><div className="home-grid">{homes.slice(0, 3).map(home => <HomeTile key={home.slug} home={home}/>)}</div><p className="collection-note">Illustrative properties · Fictional details and prices</p></div></section>
  <section className="manifesto"><div className="wrap manifesto-layout"><p className="kicker">BEYOND THE LISTING</p><div><h2>More than an address.<br/><em>A life that fits.</em></h2><p>Find room for the rituals, people and moments that make a place yours. The search should feel as thoughtful as the decision.</p><Link to="/properties" className="text-link">Discover your next chapter <MoveRight size={19}/></Link></div><div className="manifesto-index">02 / A BETTER BEGINNING</div></div></section>
  <section className="paths-section"><div className="wrap"><p className="kicker">FIND YOUR WAY HOME</p><div className="path-grid"><Link to="/properties" search={{ mode: "Rent" }} className="path-item"><span className="path-icon"><Compass size={26}/></span><span className="path-count">01</span><h3>Rent a place</h3><p>Find somewhere that feels like yours, right now.</p><ArrowUpRight className="path-arrow" size={22}/></Link><Link to="/properties" search={{ mode: "Buy" }} className="path-item"><span className="path-icon"><MapPin size={26}/></span><span className="path-count">02</span><h3>Buy a home</h3><p>Make space for the next chapter of your life.</p><ArrowUpRight className="path-arrow" size={22}/></Link><Link to="/properties" className="path-item"><span className="path-icon"><ArrowRight size={26}/></span><span className="path-count">03</span><h3>Explore places</h3><p>See what’s possible across India’s cities.</p><ArrowUpRight className="path-arrow" size={22}/></Link></div></div></section>
  <section className="final-cta"><div className="wrap final-inner"><div><p className="kicker">YOUR NEXT CHAPTER</p><h2>Good things start<br/><em>with a place.</em></h2></div><Button asChild className="final-button"><Link to="/properties">Explore homes <ArrowUpRight size={18}/></Link></Button></div></section>
</main>; }
