import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight, Bath, BedDouble, Check, MapPin, Maximize2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PropertyCard } from "@/components/property-card";
import { properties, formatPrice } from "@/lib/properties";

export const Route = createFileRoute("/property/$slug")({
  loader: ({ params }) => { const property = properties.find((item) => item.slug === params.slug); if (!property) throw notFound(); return property; },
  head: ({ loaderData }) => ({ meta: [
    { title: loaderData ? `${loaderData.title} in ${loaderData.locality} — HouseProvider.in` : "Property not found — HouseProvider.in" },
    { name: "description", content: loaderData ? `${loaderData.beds} BHK ${loaderData.type.toLowerCase()} in ${loaderData.locality}, ${loaderData.city}. Explore details, amenities and imagery.` : "This property could not be found." },
    { property: "og:title", content: loaderData ? `${loaderData.title} — HouseProvider.in` : "Property not found — HouseProvider.in" },
    { property: "og:description", content: loaderData ? `${loaderData.beds} BHK in ${loaderData.locality}, ${loaderData.city}.` : "This property could not be found." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }),
  component: PropertyDetail,
});
function PropertyDetail() {
  const property = Route.useLoaderData();
  const similar = properties.filter((item) => item.slug !== property.slug && (item.city === property.city || item.intent === property.intent)).slice(0, 3);
  return <main className="detail-page"><div className="container-wide"><div className="detail-back"><Link to="/properties"><ArrowLeft size={17}/> All homes</Link><span>SHOWCASE PROPERTY / {property.city.toUpperCase()}</span></div><div className="detail-title-row"><div><p className="eyebrow">{property.intent === "Rent" ? "FOR RENT" : "FOR SALE"} · {property.type.toUpperCase()}</p><h1>{property.title}<span className="accent-dot">.</span></h1><p><MapPin size={16}/>{property.locality}, {property.city}</p></div><div className="detail-price"><strong>{formatPrice(property)}</strong><span>{property.intent === "Rent" ? "per month" : "asking price"}</span></div></div><div className="detail-gallery"><img src={property.image} alt={`Interior or exterior of ${property.title}`} width={1008} height={768}/><span>Showcase image · Additional media unavailable</span></div><div className="detail-content"><div className="detail-main"><div className="detail-facts"><span><BedDouble size={23}/><strong>{property.beds}</strong> Bedrooms</span><span><Bath size={23}/><strong>{property.baths}</strong> Bathrooms</span><span><Maximize2 size={23}/><strong>{property.area.toLocaleString("en-IN")}</strong> sq.ft.</span></div><section className="detail-section"><p className="eyebrow">THE SPACE</p><h2>A little more about this home.</h2><p>{property.description}</p><p className="demo-disclaimer">This is a fictional showcase listing. Details, price and availability are illustrative, not a live offer.</p></section><section className="detail-section"><p className="eyebrow">THE DETAILS</p><h2>Made for everyday living.</h2><div className="amenities-grid">{property.amenities.map((amenity) => <span key={amenity}><Check size={17}/>{amenity}</span>)}<span><Check size={17}/>{property.furnishing}</span></div></section></div><aside className="detail-aside"><div className="detail-contact"><p className="eyebrow">AT A GLANCE</p><h3>{formatPrice(property)}{property.intent === "Rent" && <small> / month</small>}</h3><div className="contact-row"><span>Property type</span><strong>{property.type}</strong></div><div className="contact-row"><span>Furnishing</span><strong>{property.furnishing}</strong></div><div className="contact-row"><span>Status</span><strong>{property.available}</strong></div><p className="contact-note">Enquiries and visit scheduling are coming in a later phase. No owner contact details are available for showcase homes.</p><Button asChild className="contact-button"><Link to="/properties">Explore more homes <ArrowUpRight size={17}/></Link></Button></div></aside></div>{similar.length > 0 && <section className="similar-section"><div className="section-heading"><div><p className="eyebrow">KEEP EXPLORING</p><h2>More to discover.</h2></div><Link className="inline-arrow" to="/properties">All homes <ArrowUpRight size={18}/></Link></div><div className="property-grid">{similar.map((item, index) => <PropertyCard property={item} index={index} key={item.slug}/>)}</div></section>}</div></main>;
}