import { Link } from "@tanstack/react-router";
import { ArrowUpRight, GitCompareArrows, MapPin, ScanSearch, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import MapboxCanvas from "@/components/mapbox-canvas";
import { Reveal } from "@/components/cinematic-motion";
import { displayPrice, type Listing } from "@/lib/catalog";

type Props = { listings: Listing[] };

export function HomepageShowcase({ listings }: Props) {
  const [selected, setSelected] = useState<string | null>(null);
  const [hovered, setHovered] = useState<string | null>(null);
  const neighborhoods = Array.from(new Map(listings.map(item => [item.neighborhood, item])).values()).slice(0, 4);
  const pair = listings.slice(0, 2);
  return <>
    <section className="story-band story-match"><div className="wrap story-split"><Reveal><p className="kicker">A SEARCH THAT STARTS WITH YOU / 03</p><h2>A little more <em>in sync.</em></h2><p>Tell us what matters — from budget to BHK — and see which live listing details line up. Match explanations use only the preferences you choose.</p><Button asChild variant="outline" className="story-preferences-button mt-2 md:mt-4"><Link to="/dashboard" search={{ tab: "preferences" }}>Set your preferences <SlidersHorizontal size={16}/></Link></Button></Reveal><Reveal className="story-index" delay={0.1}><span>01 / YOUR CRITERIA</span><span>02 / LISTING FACTS</span><span>03 / A CLEARER MATCH</span><ScanSearch size={34} aria-hidden="true"/></Reveal></div></section>
    <section className="story-band story-neighborhood"><div className="wrap"><Reveal className="story-head"><div><p className="kicker">EXPLORE THE EVERYDAY / 04</p><h2>Find your <em>neighborhood.</em></h2></div></Reveal>{neighborhoods.length > 0 ? <div className="neighborhood-grid">{neighborhoods.map((item, i) => <Reveal key={item.neighborhood} delay={i * 0.05}><Link to="/properties" search={{ location: item.neighborhood }} className="neighborhood-link"><span>0{i + 1}</span><strong>{item.neighborhood}</strong><small>{item.city}</small><ArrowUpRight size={20}/></Link></Reveal>)}</div> : <div className="story-empty">Neighborhood discovery will appear here as homes are listed.</div>}</div></section>
    <section className="story-band story-map"><div className="wrap story-split"><Reveal className="story-map-copy"><p className="kicker">ANOTHER WAY TO EXPLORE / 05</p><h2>See the bigger <em>picture.</em></h2><p>Explore live homes visually, then switch between the map and the list whenever you like.</p><Button className="md:mt-2" asChild variant="outline"><Link to="/properties" search={{ view: "map" }}>Explore the map <MapPin size={16}/></Link></Button></Reveal><Reveal className="story-map-frame" delay={0.1}>{listings.length > 0 ? <MapboxCanvas homes={listings} selected={selected} hovered={hovered} onSelect={setSelected} onHover={setHovered} layer="map"/> : <div className="story-map-empty">Live property locations will appear here.</div>}</Reveal></div></section>
    <section className="story-band story-compare"><div className="wrap"><Reveal className="story-head"><div><p className="kicker">SIDE BY SIDE / 06</p><h2>Good decisions need <em>perspective.</em></h2></div></Reveal>{pair.length > 0 ? <div className="compare-editorial">{pair.map((home, i) => <Reveal key={home.slug} delay={i * 0.08}><Link to="/property/$slug" params={{ slug: home.slug }} className="compare-editorial-item"><img src={home.image} alt={"View of " + home.name} loading="lazy" width={500} height={380}/><div><span>{home.neighborhood}, {home.city}</span><strong>{home.name}</strong><small>{home.beds} BHK · {home.area.toLocaleString("en-IN")} sq.ft. · {displayPrice(home)}{home.mode === "Rent" ? " / month" : ""}</small></div></Link></Reveal>)}</div> : <div className="story-empty">Add live listings to start comparing homes here.</div>}<Reveal className="story-bottom"><Button asChild variant="outline"><Link to="/compare">Open comparison <GitCompareArrows size={16}/></Link></Button></Reveal></div></section>
    <section className="story-band story-trust"><div className="wrap story-split"><Reveal><p className="kicker">A CLEARER PICTURE / 07</p><h2>Trust starts with <em>clarity.</em></h2></Reveal><Reveal delay={0.08}><ShieldCheck size={32} aria-hidden="true"/><p>Verification is based on actual review records. Listings that have not completed verification are clearly marked.</p><Link className="text-link" to="/properties">Explore property details <ArrowUpRight size={17}/></Link></Reveal></div></section>
  </>;
}