/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminOwnersRouteImport } from './routes/admin.owners'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminVisitsRouteImport } from './routes/admin.visits'
import { Route as OwnerNewRouteImport } from './routes/owner_.new'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPublicBootstrapSuperAdminRouteImport } from './routes/api/public/bootstrap-super-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnersRoute = AdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitsRoute = AdminVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AdminRoute,
} as any)
const OwnerNewRoute = OwnerNewRouteImport.update({
  id: '/owner_/new',
  path: '/owner/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBootstrapSuperAdminRoute =
  ApiPublicBootstrapSuperAdminRouteImport.update({
    id: '/api/public/bootstrap-super-admin',
    path: '/api/public/bootstrap-super-admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bootstrap-super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bootstrap-super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/list-property': typeof ListPropertyRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/owners': typeof AdminOwnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verification': typeof AdminVerificationRoute
  '/admin/visits': typeof AdminVisitsRoute
  '/owner_/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/public/bootstrap-super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/reset-password'
    | '/signup'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/enquiries'
    | '/admin/owners'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/visits'
    | '/owner/new'
    | '/property/$slug'
    | '/admin/'
    | '/api/auth/$'
    | '/api/public/bootstrap-super-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/signup'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/enquiries'
    | '/admin/owners'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/visits'
    | '/owner/new'
    | '/property/$slug'
    | '/admin'
    | '/api/auth/$'
    | '/api/public/bootstrap-super-admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/forgot-password'
    | '/list-property'
    | '/login'
    | '/messages'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/signup'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/enquiries'
    | '/admin/owners'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/reports'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/visits'
    | '/owner_/new'
    | '/property/$slug'
    | '/admin/'
    | '/api/auth/$'
    | '/api/public/bootstrap-super-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ListPropertyRoute: typeof ListPropertyRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRoute
  PropertiesRoute: typeof PropertiesRoute
  SavedRoute: typeof SavedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  MessagesRoute: typeof MessagesRoute
  OwnerNewRoute: typeof OwnerNewRoute
  PropertySlugRoute: typeof PropertySlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPublicBootstrapSuperAdminRoute: typeof ApiPublicBootstrapSuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owners': {
      id: '/admin/owners'
      path: '/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AdminOwnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visits': {
      id: '/admin/visits'
      path: '/visits'
      fullPath: '/admin/visits'
      preLoaderRoute: typeof AdminVisitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/owner_/new': {
      id: '/owner_/new'
      path: '/owner/new'
      fullPath: '/owner/new'
      preLoaderRoute: typeof OwnerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bootstrap-super-admin': {
      id: '/api/public/bootstrap-super-admin'
      path: '/api/public/bootstrap-super-admin'
      fullPath: '/api/public/bootstrap-super-admin'
      preLoaderRoute: typeof ApiPublicBootstrapSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminOwnersRoute: typeof AdminOwnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerificationRoute: typeof AdminVerificationRoute
  AdminVisitsRoute: typeof AdminVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminOwnersRoute: AdminOwnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerificationRoute: AdminVerificationRoute,
  AdminVisitsRoute: AdminVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ListPropertyRoute: ListPropertyRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRoute,
  PropertiesRoute: PropertiesRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  MessagesRoute: MessagesRoute,
  OwnerNewRoute: OwnerNewRoute,
  PropertySlugRoute: PropertySlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPublicBootstrapSuperAdminRoute: ApiPublicBootstrapSuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
