/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as OwnerNewRouteImport } from './routes/owner_.new'
import { Route as PropertySlugRouteImport } from './routes/property.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerNewRoute = OwnerNewRouteImport.update({
  id: '/owner_/new',
  path: '/owner/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertySlugRoute = PropertySlugRouteImport.update({
  id: '/property/$slug',
  path: '/property/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/owner/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRoute
  '/properties': typeof PropertiesRoute
  '/saved': typeof SavedRoute
  '/owner_/new': typeof OwnerNewRoute
  '/property/$slug': typeof PropertySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/list-property'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/owner/new'
    | '/property/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/list-property'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/owner/new'
    | '/property/$slug'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/compare'
    | '/dashboard'
    | '/list-property'
    | '/owner'
    | '/properties'
    | '/saved'
    | '/owner_/new'
    | '/property/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  ListPropertyRoute: typeof ListPropertyRoute
  OwnerRoute: typeof OwnerRoute
  PropertiesRoute: typeof PropertiesRoute
  SavedRoute: typeof SavedRoute
  OwnerNewRoute: typeof OwnerNewRoute
  PropertySlugRoute: typeof PropertySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner_/new': {
      id: '/owner_/new'
      path: '/owner/new'
      fullPath: '/owner/new'
      preLoaderRoute: typeof OwnerNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$slug': {
      id: '/property/$slug'
      path: '/property/$slug'
      fullPath: '/property/$slug'
      preLoaderRoute: typeof PropertySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  ListPropertyRoute: ListPropertyRoute,
  OwnerRoute: OwnerRoute,
  PropertiesRoute: PropertiesRoute,
  SavedRoute: SavedRoute,
  OwnerNewRoute: OwnerNewRoute,
  PropertySlugRoute: PropertySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
